spring.application.name=Spring_Boot
product.title = my product
product.version = 2.5



app.name = MySpringBootApp
app.version = 9.0
app.author = harsh


app.file.upload-dir=/uploads
app.file.max-size=10MB

app.Email = developer@gmail.com
app.timeout = 1000